BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_inference.yaml
SIMULATOR_GPU_IDS: [6]
TORCH_GPU_ID: 6
NUM_PROCESSES: 1
TORCH_GPU_IDS: [6]
TRAINER_NAME: schedulesampler-IAW
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: logs/tensorboard_dirs/
CHECKPOINT_FOLDER: logs/checkpoints/
EVAL_CKPT_PATH_DIR: logs/checkpoints/
RESULTS_DIR: logs/eval_results/
SIMULATOR:
  HABITAT_SIM_V0:
    ALLOW_SLIDING: True

INFERENCE:
  SPLIT: test
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: logs/checkpoints/iaw_aux_eval/ckpt.48.pth
  PREDICTIONS_FILE: predictions_test.json
  FORMAT: r2r

IL:
  epochs: 50
  batch_size: 16
  lr: 1e-4
  way_lr: 1e-4
  schedule_ratio: 0.75
  decay_time: 10
  max_traj_len: 20

MODEL:
  policy_name: PolicyViewSelectionCMA
  spatial_output: False
  num_cameras: 12
  RGB_ENCODER:
    output_size: 512
  DEPTH_ENCODER:
    output_size: 256
  VISUAL_DIM:
    vis_hidden: 512
    directional: 64
    distance: 64
  INSTRUCTION_ENCODER:
    bidirectional: True
    use_pretrained_embeddings: False
    embedding_size: 256  # 256
    hidden_size: 384     # 256
  STATE_ENCODER:
    hidden_size: 768
  WAY_MODEL:
    directional: 64
    hidden_size: 768

